# Generated by Django 5.2.4 on 2025-09-01 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'writer'}, related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
